CREATE TABLE "forms" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT NOW(),
	"updatedAt" timestamp with time zone DEFAULT NOW(),
	"deletedAt" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	"pinId" uuid,
	"formName" text,
	"villageId" text,
	"name" text,
	"gender" text,
	"age" integer,
	"village" text,
	"canAttendHealthScreening" integer,
	"longTermConditions" text,
	"otherLongTermConditions" text,
	"managementMethods" text,
	"otherManagementMethods" text,
	"conditionDifficultyReasons" text,
	"otherConditionDifficultyReasons" text,
	"selfCareActions" text,
	"otherSelfCareActions" text,
	"knowWhereToFindDoctor" text,
	"otherKnowWhereToFindDoctor" text,
	"transportToClinic" text,
	"otherTransportToClinic" text,
	"medicinePurchaseLocations" text,
	"otherMedicinePurchaseLocations" text,
	"povertyCardSchemeAwareness" text,
	"otherPovertyCardSchemeAwareness" text,
	"povertyCardNonUseReasons" text,
	"toothBrushingFrequency" text,
	"otherToothBrushingFrequency" text,
	"toothbrushAndToothpasteSource" text,
	"noToothbrushOrToothpasteReasons" text,
	"otherNoToothbrushOrToothpasteReasons" text,
	"diarrhoeaDefinition" text,
	"otherDiarrhoeaDefinition" text,
	"diarrhoeaActions" text,
	"otherDiarrhoeaActions" text,
	"commonColdSymptoms" text,
	"otherCommonColdSymptoms" text,
	"commonColdActions" text,
	"otherCommonColdActions" text,
	"mskInjuryDefinition" text,
	"otherMskInjuryDefinition" text,
	"mskInjuryActions" text,
	"otherMskInjuryActions" text,
	"hypertensionDefinition" text,
	"otherHypertensionDefinition" text,
	"hypertensionActions" text,
	"otherHypertensionActions" text,
	"healthyFoodFrequency" text,
	"otherHealthyFoodFrequency" text,
	"unhealthyFoodReasons" text,
	"otherUnhealthyFoodReasons" text,
	"highCholesterolDefinition" text,
	"otherHighCholesterolDefinition" text,
	"highCholesterolActions" text,
	"otherHighCholesterolActions" text,
	"diabetesDefinition" text,
	"otherDiabetesDefinition" text,
	"diabetesActions" text,
	"otherDiabetesActions" text,
	"otherLearningAreas" text,
	"waterSources" text,
	"otherWaterSources" text,
	"unsafeWaterTypes" text,
	"otherUnsafeWaterTypes" text,
	"waterFilterAwareness" text,
	"otherWaterFilterAwareness" text,
	"waterFilterNonUseReasons" text,
	"otherWaterFilterNonUseReasons" text,
	"handwashingAfterToilet" text,
	"otherHandwashingAfterToilet" text,
	"failureReason" text,
	"status" text,
	"lastSyncedAt" timestamp with time zone,
	"lastFailedSyncAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pins" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT NOW(),
	"updatedAt" timestamp with time zone DEFAULT NOW(),
	"lat" numeric(10, 8) NOT NULL,
	"lng" numeric(11, 8) NOT NULL,
	"type" varchar(50) DEFAULT 'normal' NOT NULL,
	"name" varchar(255),
	"address" text,
	"cityVillage" varchar(255),
	"description" text,
	"deletedAt" timestamp with time zone,
	"failureReason" text,
	"status" varchar(50),
	"lastSyncedAt" timestamp with time zone,
	"lastFailedSyncAt" timestamp with time zone,
	"localImages" text DEFAULT '[]',
	"images" text DEFAULT '[]',
	"version" integer DEFAULT 1
);
--> statement-breakpoint
ALTER TABLE "forms" ADD CONSTRAINT "forms_pinId_pins_id_fk" FOREIGN KEY ("pinId") REFERENCES "public"."pins"("id") ON DELETE no action ON UPDATE no action;