CREATE TABLE "forms" (
	"id" uuid PRIMARY KEY NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now(),
	"version" integer DEFAULT 1 NOT NULL,
	"pinId" uuid,
	"status" text,
	"villageId" text NOT NULL,
	"name" text NOT NULL,
	"village" text NOT NULL,
	"gender" text,
	"age" integer,
	"canAttendHealthScreening" boolean,
	"longTermConditions" text,
	"otherLongTermConditions" text,
	"managementMethods" text,
	"otherManagementMethods" text,
	"conditionDifficultyReasons" text,
	"otherConditionDifficultyReasons" text,
	"selfCareActions" text,
	"otherSelfCareActions" text,
	"knowWhereToFindDoctor" text,
	"otherKnowWhereToFindDoctor" text,
	"transportToClinic" text,
	"otherTransportToClinic" text,
	"medicinePurchaseLocations" text,
	"otherMedicinePurchaseLocations" text,
	"povertyCardSchemeAwareness" text,
	"otherPovertyCardSchemeAwareness" text,
	"povertyCardNonUseReasons" text,
	"toothBrushingFrequency" text,
	"otherToothBrushingFrequency" text,
	"toothbrushAndToothpasteSource" text,
	"noToothbrushOrToothpasteReasons" text,
	"otherNoToothbrushOrToothpasteReasons" text,
	"diarrhoeaDefinition" text,
	"otherDiarrhoeaDefinition" text,
	"diarrhoeaActions" text,
	"otherDiarrhoeaActions" text,
	"commonColdSymptoms" text,
	"otherCommonColdSymptoms" text,
	"commonColdActions" text,
	"otherCommonColdActions" text,
	"mskInjuryDefinition" text,
	"otherMskInjuryDefinition" text,
	"mskInjuryActions" text,
	"otherMskInjuryActions" text,
	"hypertensionDefinition" text,
	"otherHypertensionDefinition" text,
	"hypertensionActions" text,
	"otherHypertensionActions" text,
	"healthyFoodFrequency" text,
	"otherHealthyFoodFrequency" text,
	"unhealthyFoodReasons" text,
	"otherUnhealthyFoodReasons" text,
	"highCholesterolDefinition" text,
	"otherHighCholesterolDefinition" text,
	"highCholesterolActions" text,
	"otherHighCholesterolActions" text,
	"diabetesDefinition" text,
	"otherDiabetesDefinition" text,
	"diabetesActions" text,
	"otherDiabetesActions" text,
	"otherLearningAreas" text,
	"waterSources" text,
	"otherWaterSources" text,
	"unsafeWaterTypes" text,
	"otherUnsafeWaterTypes" text,
	"waterFilterAwareness" text,
	"otherWaterFilterAwareness" text,
	"waterFilterNonUseReasons" text,
	"otherWaterFilterNonUseReasons" text,
	"handwashingAfterToilet" text,
	"otherHandwashingAfterToilet" text
);
--> statement-breakpoint
CREATE TABLE "pins" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now(),
	"version" integer DEFAULT 1 NOT NULL,
	"status" text,
	"lat" real NOT NULL,
	"lng" real NOT NULL,
	"name" text NOT NULL,
	"address" text,
	"cityVillage" text,
	"description" text,
	"type" text,
	"images" text
);
--> statement-breakpoint
ALTER TABLE "forms" ADD CONSTRAINT "forms_pinId_pins_id_fk" FOREIGN KEY ("pinId") REFERENCES "public"."pins"("id") ON DELETE cascade ON UPDATE no action;