CREATE TABLE "forms" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"createdAt" timestamp DEFAULT NOW(),
	"updatedAt" timestamp DEFAULT NOW(),
	"pinId" uuid NOT NULL,
	"deletedAt" timestamp,
	"village" varchar(255),
	"villageId" varchar(255),
	"failureReason" text,
	"status" varchar(50),
	"lastSyncedAt" timestamp,
	"lastFailedSyncAt" timestamp,
	"version" integer DEFAULT 1,
	"name" varchar(255),
	"canAttend" text,
	"otherCondition" text,
	"conditionDetails" text,
	"otherManagement" text,
	"otherSickAction" text,
	"knowDoctor" text,
	"ownTransport" text,
	"whereBuyMedicine" text,
	"otherBuyMedicine" text,
	"povertyCard" text,
	"brushTeeth" text,
	"otherBrushTeeth" text,
	"haveToothbrush" text,
	"diarrhoea" text,
	"diarrhoeaAction" text,
	"coldLookLike" text,
	"mskInjury" text,
	"hypertension" text,
	"cholesterol" text,
	"diabetes" text,
	"handBeforeMeal" text,
	"handAfterToilet" text,
	"eatCleanFood" text,
	"otherLearning" text,
	"otherWaterSource" text,
	"knowWaterFilters" text,
	"otherWaterFilterReason" text,
	"cholesterolAction" text,
	"coldAction" text,
	"diabetesAction" text,
	"hypertensionAction" text,
	"longTermConditions" text,
	"managementMethods" text,
	"mskAction" text,
	"notUsingWaterFilter" text,
	"unsafeWater" text,
	"waterSources" text,
	"whatDoWhenSick" text
);
--> statement-breakpoint
CREATE TABLE "pins" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	"createdAt" timestamp DEFAULT NOW(),
	"updatedAt" timestamp DEFAULT NOW(),
	"lat" numeric(10, 8) NOT NULL,
	"lng" numeric(11, 8) NOT NULL,
	"type" varchar(50) DEFAULT 'normal' NOT NULL,
	"name" varchar(255),
	"address" text,
	"cityVillage" varchar(255),
	"description" text,
	"deletedAt" timestamp,
	"failureReason" text,
	"status" varchar(50),
	"lastSyncedAt" timestamp,
	"lastFailedSyncAt" timestamp,
	"localImages" text DEFAULT '[]',
	"images" text DEFAULT '[]',
	"version" integer DEFAULT 1
);
--> statement-breakpoint
ALTER TABLE "forms" ADD CONSTRAINT "forms_pinId_pins_id_fk" FOREIGN KEY ("pinId") REFERENCES "public"."pins"("id") ON DELETE no action ON UPDATE no action;