import { sql } from 'drizzle-orm';
import { pgTable, uuid, text, boolean, varchar, decimal, integer, timestamp } from 'drizzle-orm/pg-core';

export const pins = pgTable('pins', {
  id: uuid().primaryKey().default(sql`uuid_generate_v4()`),
  createdAt: timestamp({ mode: 'date', withTimezone: true }).default(sql`NOW()`),
  updatedAt: timestamp({ mode: 'date', withTimezone: true }).default(sql`NOW()`),
  lat: decimal({ precision: 10, scale: 8 }).notNull(),
  lng: decimal({ precision: 11, scale: 8 }).notNull(),
  type: varchar({ length: 50 }).notNull().default('normal'),
  name: varchar({ length: 255 }),
  address: text(),
  cityVillage: varchar({ length: 255 }),
  description: text(),
  deletedAt: timestamp({ mode: 'date', withTimezone: true }),
  failureReason: text(),
  status: varchar({ length: 50 }),
  lastSyncedAt: timestamp({ mode: 'date', withTimezone: true }),
  lastFailedSyncAt: timestamp({ mode: 'date', withTimezone: true }),
  images: text().default('[]'),
  version: integer().default(1),
});

export const forms = pgTable('forms', {
  id: uuid().primaryKey().default(sql`uuid_generate_v4()`),
  createdAt: timestamp({ mode: 'date', withTimezone: true }).default(sql`NOW()`),
  updatedAt: timestamp({ mode: 'date', withTimezone: true }).default(sql`NOW()`),
  deletedAt: timestamp({ mode: 'date', withTimezone: true }),
  version: integer().notNull().default(1),
  pinId: uuid().references(() => pins.id),

  // General
  villageId: text(),
  name: text(),
  gender: text(),
  age: integer(),
  village: text(),
  canAttendHealthScreening: boolean(),

  // Health
  longTermConditions: text(),
  otherLongTermConditions: text(),
  managementMethods: text(),
  otherManagementMethods: text(),
  conditionDifficultyReasons: text(),
  otherConditionDifficultyReasons: text(),
  selfCareActions: text(),
  otherSelfCareActions: text(),
  knowWhereToFindDoctor: text(),
  otherKnowWhereToFindDoctor: text(),
  transportToClinic: text(),
  otherTransportToClinic: text(),
  medicinePurchaseLocations: text(),
  otherMedicinePurchaseLocations: text(),
  povertyCardSchemeAwareness: text(),
  otherPovertyCardSchemeAwareness: text(),
  povertyCardNonUseReasons: text(),
  toothBrushingFrequency: text(),
  otherToothBrushingFrequency: text(),
  toothbrushAndToothpasteSource: text(),
  noToothbrushOrToothpasteReasons: text(),
  otherNoToothbrushOrToothpasteReasons: text(),

  // Education
  diarrhoeaDefinition: text(),
  otherDiarrhoeaDefinition: text(),
  diarrhoeaActions: text(),
  otherDiarrhoeaActions: text(),
  commonColdSymptoms: text(),
  otherCommonColdSymptoms: text(),
  commonColdActions: text(),
  otherCommonColdActions: text(),
  mskInjuryDefinition: text(),
  otherMskInjuryDefinition: text(),
  mskInjuryActions: text(),
  otherMskInjuryActions: text(),
  hypertensionDefinition: text(),
  otherHypertensionDefinition: text(),
  hypertensionActions: text(),
  otherHypertensionActions: text(),
  healthyFoodFrequency: text(),
  otherHealthyFoodFrequency: text(),
  unhealthyFoodReasons: text(),
  otherUnhealthyFoodReasons: text(),
  highCholesterolDefinition: text(),
  otherHighCholesterolDefinition: text(),
  highCholesterolActions: text(),
  otherHighCholesterolActions: text(),
  diabetesDefinition: text(),
  otherDiabetesDefinition: text(),
  diabetesActions: text(),
  otherDiabetesActions: text(),
  otherLearningAreas: text(),

  // Water
  waterSources: text(),
  otherWaterSources: text(),
  unsafeWaterTypes: text(),
  otherUnsafeWaterTypes: text(),
  waterFilterAwareness: text(),
  otherWaterFilterAwareness: text(),
  waterFilterNonUseReasons: text(),
  otherWaterFilterNonUseReasons: text(),
  handwashingAfterToilet: text(),
  otherHandwashingAfterToilet: text(),

  // Local-only fields (sync tracking)
  failureReason: text(),
  status: text(),
  lastSyncedAt: timestamp({ mode: 'date', withTimezone: true }),
  lastFailedSyncAt: timestamp({ mode: 'date', withTimezone: true }),
});
