import { sql } from 'drizzle-orm';
import { pgTable, uuid, text, varchar, decimal, integer, timestamp } from 'drizzle-orm/pg-core';

export const pins = pgTable('pins', {
  id: uuid('id')
    .primaryKey()
    .default(sql`uuid_generate_v4()`),
  createdAt: timestamp('createdAt', { mode: 'date' }).default(sql`NOW()`),
  updatedAt: timestamp('updatedAt', { mode: 'date' }).default(sql`NOW()`),
  lat: decimal('lat', { precision: 10, scale: 8 }).notNull(),
  lng: decimal('lng', { precision: 11, scale: 8 }).notNull(),
  type: varchar('type', { length: 50 }).notNull().default('normal'),
  name: varchar('name', { length: 255 }),
  address: text('address'),
  cityVillage: varchar('cityVillage', { length: 255 }),
  description: text('description'),
  deletedAt: timestamp('deletedAt', { mode: 'date' }),
  failureReason: text('failureReason'),
  status: varchar('status', { length: 50 }),
  lastSyncedAt: timestamp('lastSyncedAt', { mode: 'date' }),
  lastFailedSyncAt: timestamp('lastFailedSyncAt', { mode: 'date' }),
  localImages: text('localImages').default('[]'),
  images: text('images').default('[]'),
  version: integer('version').default(1),
});

export const forms = pgTable('forms', {
  id: uuid('id')
    .primaryKey()
    .default(sql`uuid_generate_v4()`),
  createdAt: timestamp('createdAt', { mode: 'date' }).default(sql`NOW()`),
  updatedAt: timestamp('updatedAt', { mode: 'date' }).default(sql`NOW()`),
  pinId: uuid('pinId')
    .notNull()
    .references(() => pins.id),
  deletedAt: timestamp('deletedAt', { mode: 'date' }),
  village: varchar('village', { length: 255 }),
  villageId: varchar('villageId', { length: 255 }),
  failureReason: text('failureReason'),
  status: varchar('status', { length: 50 }),
  lastSyncedAt: timestamp('lastSyncedAt', { mode: 'date' }),
  lastFailedSyncAt: timestamp('lastFailedSyncAt', { mode: 'date' }),
  version: integer('version').default(1),
  name: varchar('name', { length: 255 }),

  // Health survey fields
  canAttend: text('canAttend'),
  otherCondition: text('otherCondition'),
  conditionDetails: text('conditionDetails'),
  otherManagement: text('otherManagement'),
  otherSickAction: text('otherSickAction'),
  knowDoctor: text('knowDoctor'),
  ownTransport: text('ownTransport'),
  whereBuyMedicine: text('whereBuyMedicine'),
  otherBuyMedicine: text('otherBuyMedicine'),
  povertyCard: text('povertyCard'),
  brushTeeth: text('brushTeeth'),
  otherBrushTeeth: text('otherBrushTeeth'),
  haveToothbrush: text('haveToothbrush'),
  diarrhoea: text('diarrhoea'),
  diarrhoeaAction: text('diarrhoeaAction'),
  coldLookLike: text('coldLookLike'),
  mskInjury: text('mskInjury'),
  hypertension: text('hypertension'),
  cholesterol: text('cholesterol'),
  diabetes: text('diabetes'),
  handBeforeMeal: text('handBeforeMeal'),
  handAfterToilet: text('handAfterToilet'),
  eatCleanFood: text('eatCleanFood'),
  otherLearning: text('otherLearning'),
  otherWaterSource: text('otherWaterSource'),
  knowWaterFilters: text('knowWaterFilters'),
  otherWaterFilterReason: text('otherWaterFilterReason'),
  cholesterolAction: text('cholesterolAction'),
  coldAction: text('coldAction'),
  diabetesAction: text('diabetesAction'),
  hypertensionAction: text('hypertensionAction'),
  longTermConditions: text('longTermConditions'),
  managementMethods: text('managementMethods'),
  mskAction: text('mskAction'),
  notUsingWaterFilter: text('notUsingWaterFilter'),
  unsafeWater: text('unsafeWater'),
  waterSources: text('waterSources'),
  whatDoWhenSick: text('whatDoWhenSick'),
});
